### ISSUE TITLE
failed to upgrade this module to vault due to version of protobuf

### ISSUE THREAD

**Issue by likexian** [hashicorp/go-kms-wrapping#15]
Hello,

This module imports the latest version of `protobuf` (v1.4.0-rc.4), but vault is using an old version of `protobuf` (v1.3.2), they are incompatible. So it is impossible to upgrade the version of `go-kms-wrapping` in vault.

The solutions:
1. upgrade the `protobuf` version of vault, this is a very very big works.
2. downgrade the `protobuf` version of `go-kms-wrapping`, is it possible?

Please help, thanks.

**Comment by jefferai** [comment]
Unfortunately, like many dependency issues these days, etcd is the issue here with respect to protobuf and updating Vault. At the moment Vault uses an older version of this library while it relies on the etcd dep. Simply don't update this dependency while building Vault and you'll be fine.

Note that Vault's api and sdk modules do not rely on this.
